server:
  port: 8080
spring:
  application:
    name: api-gateway
  mail:
      host: mtp.163.com
      username: spring_boot@163.com
      password: abc123455
      properties:
         mail:
           smtp:
             auth: true
             starttls:
               enable: true
               required: false
  freemarker:
    charset: utf-8
    content-type: text/html;charset=UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
    settings.default_encoding: UTF-8
    settings.auto_import: common/common.ftl as common
    allow-session-override: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  healthcheck:
    enabled: true
logbook:
  write:
    level: info
  format:
    style: curl
domain.name: 127.0.0.1:8080
file.prefix: http://127.0.0.1:80/
file.path: D:/image/

user.service.name: user-service
house.service.name: house
comment.service.name: comment
management:
  port: 8023

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 2000
hystrix.threadpool.default.coreSize: 1
hystrix.threadpool.default.maxQueueSize: 1
hystrix.threadpool.default.maximumSize: 1

hystrix.command.default.circuitBreaker.errorThresholdPercentage: 1
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds: 100000